"""add Department

Revision ID: 7340ba6e1bfb
Revises: 25d52caabbad
Create Date: 2024-06-29 13:47:27.222578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7340ba6e1bfb'
down_revision = '25d52caabbad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
