"""rename address

Revision ID: 857ae8e99d2e
Revises: 8c4c38bbc474
Create Date: 2024-06-29 13:51:58.882006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '857ae8e99d2e'
down_revision = '8c4c38bbc474'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
     op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###
