"""rename department

Revision ID: 8c4c38bbc474
Revises: 7340ba6e1bfb
Create Date: 2024-06-29 13:49:48.905986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c4c38bbc474'
down_revision = '7340ba6e1bfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
     op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
